<?php /*

,--.     ,--.                       ,--------.,--.   ,--.
|  |     |  |,--.,--. ,--,--.,--,--,'--.  .--'|   `.'   |
|  |,--. |  ||  ||  |' ,-.  ||      \  |  |   |  |'.'|  |
|  ||  '-'  /'  ''  '\ '-'  ||  ||  |  |  |   |  |   |  |
`--' `-----'  `----'  `--`--'`--''--'  `--'   `--'   `--'

Made for PHP version : 7.3.12
Made by Iwan van der Wal
 */ ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Include the bootstrap css and meta links. -->
    <?php
    $this->get_part('meta');
    $this->get_part('css');
    require_once("script/svg-helper.php");
    ?>
    <!-- Pagina Titel -->
    <title>Starter_Template</title>
    <!-- Page icons -->
    <link rel="shortcut icon" href="<?= $this->urlArr['baseUrl'] ?>img/icon/icon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="200x200" href="<?= $this->urlArr['baseUrl'] ?>img/icon/icon.ico">
    <link rel="icon" href="<?= $this->urlArr['baseUrl'] ?>img/icon/icon.ico" type="image/x-icon">
    <link rel="icon" href="<?= $this->urlArr['baseUrl'] ?>img/icon/icon.ico">
</head>
<body>
<!-- Page Content -->
<main id="contents">
    <!--Navbar-->
    <?php $this->get_part('navbar'); ?>
    <!--Content-->
    <section class="content">